# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jackson Pierce
title: Mechanical Engineering Student, University of Michigan
email: piercejp@umich.edu
website: jax1828.github.io
phone: (313)-410-5863

# Dark Mode (true/false/never)
darkmode: false

# Social links
#instagram_username: jaxpierce1828
linkedin_username: piercejp

# About Section
about_title: About Me
about_profile_image: headshot.png
about_content: | # this will include new lines to allow paragraphs

  Hello! I'm Jackson, a Mechanical Engineering student at the University of Michigan. I am passionate about nuclear power, mechanical design, biomechanics, and automotive engineering.
  
  Software: <mark>AutoCAD</mark> <mark>Solidworks</mark> <mark>Siemens NX</mark> <mark>Fusion360</mark> <mark>Inventor</mark> <mark>MATLAB & Simulink</mark> <mark>Adobe InDesign</mark> <mark>ArcGIS</mark> 
  
  <mark>Altair Hyperworks</mark> <mark>Python</mark> <mark>LaTeX</mark> <mark>ADAMs</mark>
  
  Machines: <mark>Mill</mark>, <mark>Lathe</mark>, <mark>Waterjet</mark>, <mark>CNC Router</mark>, <mark>FDM Printing</mark>
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Low-Cost EMG Controlled Prosthetic Leg
        sub_title: BME 2920, WSU
        caption: Fall 2023, Winter 2024
        quote: >
          Mechanical Lead
        description: |
          • Designed and modeled fully articulated, brushless motor-powered knee joint mechanism
          
          • Worked alongside university machinist advisors to produce milled aluminum prototype
          
          • Developed multiple physical and digital models showcasing various features of the prosthesis

      - layout: left
        title: Mechanical Engineering Robotics Competition
        sub_title: ME250, UofM
        caption: Winter 2025
        quote: >
          1st Place Winner!
        description: |
          • Designed, fabricated, and assembled a small robot to complete a series of challenges alongside a team of peers,
            achieving a first-place finish and the honor of having our project displayed for future classes

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Quality Engineering Intern
        #link:
        sub_title: OPMobility (Plastic Omnium)
        caption: Summer 2025
        quote: >
          Worked alongside warranty engineers and lab technicians to analyze failed parts and prompt internal process improvements.
        description: |
          •	Developed Arduino-based electrical testing solution, reducing cycle time by 80%
          
          •	Assisted in automating data collection and analysis using Microsoft Power Automate and Copilot, integrating AI classification to reduce tedium and reallocate engineering resources, saving 20+ hours of company time each week
         
          •	Analyzed failed warranty parts physically using 3D microscopy, FTIR, and CAN functional testing equipment, then applied this data to advise design refinements

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Michigan
        caption: 2024-2026
        sub_title: BS Mechanical Engineering
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          • GPA: 3.889
          
          • Dean's List
      - layout: left
        title: Wayne State University
        caption: 2022-2024
        sub_title: Transferred to Michigan
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          • GPA: 3.943
          
          • Dean's List

  - title: Organizations
    layout: list
    content:
      - layout: left
        title: MMB
        link: https://michiganmarchingband.com/
        sub_title: Michigan Marching Band
        caption: 2024 - Present
        quote: >
          "...When a hush settles over that stadium and we all anxiously wait for that simple 4 word command to eminate out of the P.A. system. I can hear it now! "Band take the field!" and out of that eastern tunnel pour 215 well 
          drilled, well disciplined Michigan bandsmen. They pour over the Eastern sideline and they form the big block M and they play the greatest college fight song ever written! The Michigan Victors!"

          -Bob Ufer
        description: |
          • Euphonium Section Leader

          • Equipment Staff

      - layout: left
        title: Kappa Kappa Psi
        link: https://kkyumich.wixsite.com/kkpsinu
        sub_title: National Honorary Band Fraternity
        caption: 2025 - Present
        quote: >
          "Kappa Kappa Psi is a co-educational fraternal organization that advances college and university bands for the benefit of its members and society through dedicated service and support to the bands, encouragement of musical growth, lifelong educational experiences, leadership opportunities, and recognition."
        description: |
          • Rituals and Regalia Chair

          • Music Committee Chair

          • Engaged in myriad professional development, service, and leadership activities specifically pertaining to the practice of music, including the arrangement and direction thereof.
          
      - layout: left
        title: First Robotics Competition
        link: https://www.thebluealliance.com/team/7196
        sub_title: Academy of the Americas / Team 7196
        caption: 2022 - Present
        quote: >
          “...it’s like the WWF, but for smart people!” -President George H. W. Bush (alledgedly)
        description: |
          • Teach and advise elementary and high school robotics students in technical concepts, including physics, mechanical design, and project planning, as well as the various soft skills required for successful collaborative engineering.

          
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

# Custom styles for light and dark modes
additional_css:
  - assets/css/custom.css

plugins:
  - jekyll-seo-tag
