# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jackson Pierce
title: Mechanical Engineering Student at the University of Michigan
email: piercejp@umich.edu
website: jax1828.github.io
phone: (313)-410-5863

# Dark Mode (true/false/never)
darkmode: false

# Social links
instagram_username: jaxpierce1828
linkedin_username: piercejp

# About Section
about_profile_image: IMG_5259.PNG
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm Jackson! Website coming soon ;)

  <nav style="text-align: center; margin: 20px 0;">
    <a href="#about-me" class="menu-link">Home</a> |
    <a href="#projects" class="menu-link">Projects</a> |
    <a href="#experience" class="menu-link">Experience</a> |
    <a href="#education" class="menu-link">Education</a> |
    <a href="#volunteering" class="menu-link">Volunteering</a> |
    <a href="#organizations" class="menu-link">Organizations</a>
  </nav>

  I am most skilled in: <mark>Engineering</mark> and <mark>Music</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Low Cost EMG Controlled Prosthetic Leg
        description: |
          Prototype

  - title: Experience
    layout: list
    content:
      - layout: left
        title: OCC
        link: occsystems.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by digging holes and making game-changing products like the *not a flamethrower*
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard, and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

# Custom styles for light and dark modes
additional_css:
  - assets/css/custom.css

plugins:
  - jekyll-seo-tag
